### ISSUE TITLE
Using QNAP Nas certificate

### ISSUE THREAD

**Issue by Robb-Fr** [umireon/vaultwarden-qnap#1]
Hello !
Thanks a lot for this example. In order to avoid bothering with solving ACME challenge stuff (or exposing the Nas to the internet) for enabling secure connexion, do you think there would be a way to use the automatically received certificate by the QNAP certificate app for a containered vaultwarden?
This of course would assume you access the vaultwarden through the [your nas name].myqnapcloud.com domain name which might be confusing, but could work.

Have you any thought on it/an idea on how to properly update your proposed docker-compose file?

Thanks a lot!

**Comment by umireon** [comment]
Thanks for checking this repo!

You can investigate how the QNAP certificate app stores the Let's Encrypt certificate and the Let's Encrypt key via the administrative SSH connection which is a builtin feature of the QNAP NAS and you could create a small helper Docker image that extracts the QNAP certificate into other format which can be used with the other application (e.g. Traefik) by writing a script in your favorite programming language like Go or Shellscript and, for example, saving the extracted certificate on a named volume might enable us to use the QNAP certificate with traefik.

**Comment by Robb-Fr** [comment]
Hey, thanks a lot for your suggestions ! I will reopen this if I find something interesting :)
