### ISSUE TITLE
KISS

### ISSUE THREAD

**Issue by oywino** [umireon/vaultwarden-qnap#2]
This guide is unnecessary  complicated.
1. Just install vaultwarden/server:1.30.5  (or latest) in Container Station using NAT defaults and the following settings: 
ROCKET_ENV            staging
ROCKET_PORT          80
ROCKET_WORKERS  10
Add whatever timezone and language variables you need.

Choose a free host port and forward it to container port 3012/TCP
Forward host port 8100 to container port 80/TCP

Then add a shared folder path  /data to any shared folder of your choice.

Finally, set up Traefik, Apache, NGINX or any Reverse Proxy server of your choice and route incoming traffic from a dedicated domain to [NAS-IP]:8100
Make sure your Reverse Proxy is set for HTTPS.

There's no need to expose your VaultWarden instance directly to the internet.

**Comment by umireon** [comment]
What do you want me?

**Comment by umireon** [comment]
Closing this as not related to this repository
